import { promises as fs } from 'fs'
import path from 'path'

type RangeFilter = {
  gte?: string
  lte?: string
  in?: string[]
}

type Where = Record<string, unknown>

type OrderBy = Record<string, 'asc' | 'desc'>

type EmployeeRecord = {
  id: string
  name: string
  startDate: string
  monthlySalary: number
  firstSundayPattern: string
  salaryCalculationMethod: string
  createdAt: string
  updatedAt: string
}

type AttendanceRecord = {
  id: string
  date: string
  status: string
  payableValue: number
  note: string | null
  isAutoGenerated: boolean
  isManualOverride: boolean
  employeeId: string
  createdAt: string
  updatedAt: string
}

type HolidayRecord = {
  id: string
  date: string
  name: string
  recurring: boolean
  createdAt: string
  updatedAt: string
}

type StoreData = {
  employees: EmployeeRecord[]
  attendance: AttendanceRecord[]
  holidays: HolidayRecord[]
}

type QueryOptions = {
  where?: Where
  orderBy?: OrderBy
  include?: Record<string, unknown>
  take?: number
}

type CreateAttendanceInput = Omit<AttendanceRecord, 'id' | 'createdAt' | 'updatedAt' | 'note'> & {
  note?: string | null
}

const emptyStore = (): StoreData => ({
  employees: [],
  attendance: [],
  holidays: [],
})

const storeFile =
  process.env.WORKSYNC_DATA_FILE ||
  (process.env.VERCEL
    ? '/tmp/worksync-data.json'
    : path.join(process.cwd(), 'db', 'worksync-data.json'))

const globalForStore = globalThis as unknown as {
  worksyncStore: StoreData | undefined
  worksyncReady: Promise<void> | undefined
  worksyncWrite: Promise<void> | undefined
}

function now() {
  return new Date().toISOString()
}

function createId() {
  return crypto.randomUUID()
}

function isRangeFilter(value: unknown): value is RangeFilter {
  return typeof value === 'object' && value !== null
}

function matchesWhere<T extends Record<string, unknown>>(item: T, where?: Where) {
  if (!where) return true

  return Object.entries(where).every(([key, expected]) => {
    const actual = item[key]

    if (isRangeFilter(expected)) {
      const actualString = String(actual ?? '')
      if (typeof expected.gte === 'string' && actualString < expected.gte) return false
      if (typeof expected.lte === 'string' && actualString > expected.lte) return false
      if (Array.isArray(expected.in) && !expected.in.includes(actualString)) return false
      return true
    }

    return actual === expected
  })
}

function sortRows<T extends Record<string, unknown>>(rows: T[], orderBy?: OrderBy) {
  if (!orderBy) return rows
  const [[field, direction]] = Object.entries(orderBy)
  if (!field) return rows

  return [...rows].sort((a, b) => {
    const av = String(a[field] ?? '')
    const bv = String(b[field] ?? '')
    return direction === 'desc' ? bv.localeCompare(av) : av.localeCompare(bv)
  })
}

async function loadStore() {
  if (globalForStore.worksyncStore) return globalForStore.worksyncStore

  try {
    const raw = await fs.readFile(storeFile, 'utf8')
    globalForStore.worksyncStore = JSON.parse(raw) as StoreData
  } catch {
    globalForStore.worksyncStore = emptyStore()
    await saveStore(globalForStore.worksyncStore)
  }

  return globalForStore.worksyncStore
}

async function saveStore(data: StoreData) {
  await fs.mkdir(path.dirname(storeFile), { recursive: true })
  globalForStore.worksyncWrite = (globalForStore.worksyncWrite ?? Promise.resolve()).then(() =>
    fs.writeFile(storeFile, JSON.stringify(data, null, 2), 'utf8')
  )
  await globalForStore.worksyncWrite
}

async function withStore<T>(fn: (data: StoreData) => T | Promise<T>) {
  await ensureDatabase()
  const data = await loadStore()
  return fn(data)
}

function includeAttendanceEmployee(record: AttendanceRecord, include?: Record<string, unknown>) {
  if (!include?.employee) return record
  const employee = globalForStore.worksyncStore?.employees.find((item) => item.id === record.employeeId)
  return {
    ...record,
    employee: employee ? { name: employee.name } : null,
  }
}

export async function ensureDatabase() {
  globalForStore.worksyncReady ??= (async () => {
    await fs.mkdir(path.dirname(storeFile), { recursive: true })
    await loadStore()
  })()

  await globalForStore.worksyncReady
}

export const db = {
  employee: {
    async findFirst(_options?: QueryOptions) {
      return withStore((data) => data.employees[0] ?? null)
    },
    async findUnique({ where }: { where: { id: string } }) {
      return withStore((data) => data.employees.find((item) => item.id === where.id) ?? null)
    },
    async count() {
      return withStore((data) => data.employees.length)
    },
    async create({ data: input }: { data: Omit<EmployeeRecord, 'id' | 'createdAt' | 'updatedAt'> }) {
      return withStore(async (data) => {
        const timestamp = now()
        const employee: EmployeeRecord = {
          id: createId(),
          createdAt: timestamp,
          updatedAt: timestamp,
          ...input,
        }
        data.employees = [employee]
        await saveStore(data)
        return employee
      })
    },
    async update({ where, data: input }: { where: { id: string }; data: Partial<EmployeeRecord> }) {
      return withStore(async (data) => {
        const employee = data.employees.find((item) => item.id === where.id)
        if (!employee) throw new Error(`Employee not found: ${where.id}`)
        Object.assign(employee, input, { updatedAt: now() })
        await saveStore(data)
        return employee
      })
    },
    async delete({ where }: { where: { id: string } }) {
      return withStore(async (data) => {
        const index = data.employees.findIndex((item) => item.id === where.id)
        if (index === -1) throw new Error(`Employee not found: ${where.id}`)
        const [employee] = data.employees.splice(index, 1)
        data.attendance = data.attendance.filter((item) => item.employeeId !== where.id)
        await saveStore(data)
        return employee
      })
    },
  },
  attendance: {
    async findFirst(options: QueryOptions = {}) {
      return withStore((data) => {
        const record = data.attendance.find((item) => matchesWhere(item, options.where))
        return record ? includeAttendanceEmployee(record, options.include) : null
      })
    },
    async findMany(options: QueryOptions = {}) {
      return withStore((data) =>
        sortRows(
          data.attendance
            .filter((item) => matchesWhere(item, options.where))
            .map((item) => includeAttendanceEmployee(item, options.include)),
          options.orderBy
        ).slice(0, options.take ?? undefined)
      )
    },
    async create({ data: input }: { data: CreateAttendanceInput }) {
      return withStore(async (data) => {
        const timestamp = now()
        const record: AttendanceRecord = {
          id: createId(),
          createdAt: timestamp,
          updatedAt: timestamp,
          ...input,
          note: input.note ?? null,
        }
        data.attendance.push(record)
        await saveStore(data)
        return record
      })
    },
    async createMany({ data: rows }: { data: CreateAttendanceInput[] }) {
      return withStore(async (data) => {
        const timestamp = now()
        for (const input of rows) {
          data.attendance.push({
            id: createId(),
            createdAt: timestamp,
            updatedAt: timestamp,
            ...input,
            note: input.note ?? null,
          })
        }
        await saveStore(data)
        return { count: rows.length }
      })
    },
    async update({ where, data: input }: { where: { id: string }; data: Partial<AttendanceRecord> }) {
      return withStore(async (data) => {
        const record = data.attendance.find((item) => item.id === where.id)
        if (!record) throw new Error(`Attendance record not found: ${where.id}`)
        Object.assign(record, input, { updatedAt: now() })
        await saveStore(data)
        return record
      })
    },
    async delete({ where }: { where: { id: string } }) {
      return withStore(async (data) => {
        const index = data.attendance.findIndex((item) => item.id === where.id)
        if (index === -1) throw new Error(`Attendance record not found: ${where.id}`)
        const [record] = data.attendance.splice(index, 1)
        await saveStore(data)
        return record
      })
    },
    async deleteMany({ where }: { where?: Where } = {}) {
      return withStore(async (data) => {
        const before = data.attendance.length
        data.attendance = data.attendance.filter((item) => !matchesWhere(item, where))
        await saveStore(data)
        return { count: before - data.attendance.length }
      })
    },
  },
  holiday: {
    async findMany(options: QueryOptions = {}) {
      return withStore((data) => sortRows(data.holidays.filter((item) => matchesWhere(item, options.where)), options.orderBy))
    },
    async findUnique({ where }: { where: { date: string } }) {
      return withStore((data) => data.holidays.find((item) => item.date === where.date) ?? null)
    },
    async create({ data: input }: { data: Omit<HolidayRecord, 'id' | 'createdAt' | 'updatedAt'> }) {
      return withStore(async (data) => {
        const timestamp = now()
        const holiday: HolidayRecord = {
          id: createId(),
          createdAt: timestamp,
          updatedAt: timestamp,
          ...input,
        }
        data.holidays.push(holiday)
        await saveStore(data)
        return holiday
      })
    },
    async delete({ where }: { where: { date: string } }) {
      return withStore(async (data) => {
        const index = data.holidays.findIndex((item) => item.date === where.date)
        if (index === -1) throw new Error(`Holiday not found: ${where.date}`)
        const [holiday] = data.holidays.splice(index, 1)
        await saveStore(data)
        return holiday
      })
    },
  },
}
