import { PrismaClient } from '@prisma/client'

if (!process.env.DATABASE_URL) {
  process.env.DATABASE_URL =
    process.env.NODE_ENV === 'production'
      ? 'file:/tmp/worksync.db'
      : 'file:../db/custom.db'
}

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined
  prismaSchemaReady: Promise<void> | undefined
}

// Force new PrismaClient if the cached one is missing models (schema changes)
if (globalForPrisma.prisma && typeof (globalForPrisma.prisma as unknown as Record<string, unknown>).holiday === 'undefined') {
  globalForPrisma.prisma = undefined
}

export const db =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: [],
  })

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = db

export async function ensureDatabase() {
  if (!process.env.DATABASE_URL?.startsWith('file:')) return

  globalForPrisma.prismaSchemaReady ??= (async () => {
    await db.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS "Employee" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "name" TEXT NOT NULL,
        "startDate" TEXT NOT NULL,
        "monthlySalary" REAL NOT NULL,
        "firstSundayPattern" TEXT NOT NULL DEFAULT 'HALF_DAY',
        "salaryCalculationMethod" TEXT NOT NULL DEFAULT 'FIXED_30_DAYS',
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL
      )
    `)

    await db.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS "Attendance" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "date" TEXT NOT NULL,
        "status" TEXT NOT NULL DEFAULT 'FULL_DAY',
        "payableValue" REAL NOT NULL DEFAULT 1.0,
        "note" TEXT,
        "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
        "isManualOverride" BOOLEAN NOT NULL DEFAULT false,
        "employeeId" TEXT NOT NULL,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "Attendance_employeeId_fkey"
          FOREIGN KEY ("employeeId") REFERENCES "Employee" ("id")
          ON DELETE CASCADE ON UPDATE CASCADE
      )
    `)

    await db.$executeRawUnsafe(`
      CREATE UNIQUE INDEX IF NOT EXISTS "Attendance_date_employeeId_key"
      ON "Attendance"("date", "employeeId")
    `)

    await db.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS "Holiday" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "date" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "recurring" BOOLEAN NOT NULL DEFAULT false,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL
      )
    `)

    await db.$executeRawUnsafe(`
      CREATE UNIQUE INDEX IF NOT EXISTS "Holiday_date_key"
      ON "Holiday"("date")
    `)
  })()

  await globalForPrisma.prismaSchemaReady
}
