import { create } from 'zustand'

// Types
export type AttendanceStatus = 'FULL_DAY' | 'HALF_DAY' | 'ABSENT' | 'OFF'
export type SalaryMethod = 'CALENDAR_DAYS' | 'FIXED_30_DAYS' | 'WORKING_DAYS'
export type SundayPattern = 'HALF_DAY' | 'FULL_OFF'
export type AppScreen = 'onboarding' | 'profile-setup' | 'dashboard' | 'calendar' | 'sunday-tracker' | 'salary' | 'date-range' | 'monthly-report' | 'analytics' | 'settings' | 'holiday-manager' | 'empty'
export type NavTab = 'dashboard' | 'calendar' | 'reports' | 'settings'

export interface Employee {
  id: string
  name: string
  startDate: string
  monthlySalary: number
  firstSundayPattern: SundayPattern
  salaryCalculationMethod: SalaryMethod
  createdAt: string
  updatedAt: string
}

export interface AttendanceRecord {
  id: string
  date: string
  status: AttendanceStatus
  payableValue: number
  note: string | null
  isAutoGenerated: boolean
  isManualOverride: boolean
  employeeId: string
}

export interface SalaryBreakdown {
  year: number
  month: number
  totalCalendarDays: number
  workingPayableCapacity: number
  perDaySalary: number
  totalPayableDays: number
  totalSalary: number
  breakdown: Array<{
    date: string
    status: string
    payableValue: number
    dailyPayment: number
  }>
}

export interface DateRangeSalary {
  totalSalary: number
  totalPayableDays: number
  months: SalaryBreakdown[]
}

interface AppState {
  // Navigation
  currentScreen: AppScreen
  activeTab: NavTab
  setCurrentScreen: (screen: AppScreen) => void
  setActiveTab: (tab: NavTab) => void

  // Employee profile
  employee: Employee | null
  setEmployee: (emp: Employee | null) => void
  loading: boolean
  setLoading: (l: boolean) => void

  // Selected month for views
  selectedMonth: number
  selectedYear: number
  setSelectedMonth: (m: number) => void
  setSelectedYear: (y: number) => void

  // Attendance records
  attendanceRecords: AttendanceRecord[]
  setAttendanceRecords: (records: AttendanceRecord[]) => void

  // Edit bottom sheet
  editDate: string | null
  setEditDate: (date: string | null) => void

  // Salary data
  salaryData: SalaryBreakdown | null
  setSalaryData: (data: SalaryBreakdown | null) => void

  // Date range report
  dateRangeFrom: string
  dateRangeTo: string
  dateRangeSalary: DateRangeSalary | null
  setDateRangeFrom: (d: string) => void
  setDateRangeTo: (d: string) => void
  setDateRangeSalary: (data: DateRangeSalary | null) => void

  // Toast
  toastMessage: string | null
  toastType: 'success' | 'error' | 'info'
  showToast: (message: string, type?: 'success' | 'error' | 'info') => void
  clearToast: () => void

  // Data loading state
  dataLoading: boolean
  setDataLoading: (l: boolean) => void

  // Cache: last fetched month/year to avoid redundant API calls
  lastFetchedMonth: number | null
  lastFetchedYear: number | null

  // Fetch helpers
  fetchProfile: () => Promise<void>
  fetchAttendance: (from: string, to: string) => Promise<void>
  fetchSalary: (month: number, year: number) => Promise<void>
  fetchMonthData: (force?: boolean) => Promise<void>
  generateAttendance: () => Promise<void>
}

// Safe date getter that works for both SSR and client
function getInitialDate() {
  if (typeof window !== 'undefined') {
    const d = new Date()
    return { month: d.getMonth() + 1, year: d.getFullYear() }
  }
  return { month: 1, year: 2026 }
}

function getMonthRange(month: number, year: number) {
  const from = `${year}-${String(month).padStart(2, '0')}-01`
  const daysInMonth = new Date(year, month, 0).getDate()
  const to = `${year}-${String(month).padStart(2, '0')}-${String(daysInMonth).padStart(2, '0')}`
  return { from, to }
}

const initialDate = getInitialDate()

export const useAppStore = create<AppState>((set, get) => ({
  currentScreen: 'onboarding',
  activeTab: 'dashboard',
  setCurrentScreen: (screen) => set({ currentScreen: screen }),
  setActiveTab: (tab) => {
    set({ activeTab: tab })
    const screenMap: Record<NavTab, AppScreen> = {
      dashboard: 'dashboard',
      calendar: 'calendar',
      reports: 'salary',
      settings: 'settings',
    }
    set({ currentScreen: screenMap[tab] })
  },

  employee: null,
  setEmployee: (emp) => set({ employee: emp }),
  loading: false,
  setLoading: (l) => set({ loading: l }),

  selectedMonth: initialDate.month,
  selectedYear: initialDate.year,
  setSelectedMonth: (m) => set({ selectedMonth: m }),
  setSelectedYear: (y) => set({ selectedYear: y }),

  attendanceRecords: [],
  setAttendanceRecords: (records) => set({ attendanceRecords: records }),

  editDate: null,
  setEditDate: (date) => set({ editDate: date }),

  salaryData: null,
  setSalaryData: (data) => set({ salaryData: data }),

  dateRangeFrom: '',
  dateRangeTo: '',
  dateRangeSalary: null,
  setDateRangeFrom: (d) => set({ dateRangeFrom: d }),
  setDateRangeTo: (d) => set({ dateRangeTo: d }),
  setDateRangeSalary: (data) => set({ dateRangeSalary: data }),

  toastMessage: null,
  toastType: 'info',
  showToast: (message, type = 'info') => {
    set({ toastMessage: message, toastType: type })
    setTimeout(() => set({ toastMessage: null }), 3000)
  },
  clearToast: () => set({ toastMessage: null }),

  dataLoading: false,
  setDataLoading: (l) => set({ dataLoading: l }),

  lastFetchedMonth: null,
  lastFetchedYear: null,

  fetchProfile: async () => {
    try {
      const res = await fetch('/api/profile')
      if (res.ok) {
        const data = await res.json()
        if (data.employee) {
          set({ employee: data.employee })
          return
        }
      }
      set({ employee: null })
    } catch {
      set({ employee: null })
    }
  },

  fetchAttendance: async (from, to) => {
    try {
      const emp = get().employee
      if (!emp) return
      const res = await fetch(`/api/attendance?from=${from}&to=${to}&employeeId=${emp.id}`)
      if (res.ok) {
        const data = await res.json()
        set({ attendanceRecords: data.records || [] })
      }
    } catch {
      // silent
    }
  },

  fetchSalary: async (month, year) => {
    try {
      const res = await fetch(`/api/salary?month=${month}&year=${year}`)
      if (res.ok) {
        const data = await res.json()
        set({ salaryData: data.salary || data })
      }
    } catch {
      // silent
    }
  },

  fetchMonthData: async (force = false) => {
    const { employee, selectedMonth, selectedYear, lastFetchedMonth, lastFetchedYear } = get()
    if (!employee) return

    // Skip if already fetched this month/year (unless forced)
    if (!force && lastFetchedMonth === selectedMonth && lastFetchedYear === selectedYear) {
      return
    }

    set({ dataLoading: true })
    const { from, to } = getMonthRange(selectedMonth, selectedYear)
    await get().fetchAttendance(from, to)

    // No auto-generation — user must fill in all data manually
    await get().fetchSalary(selectedMonth, selectedYear)
    set({ dataLoading: false, lastFetchedMonth: selectedMonth, lastFetchedYear: selectedYear })
  },

  generateAttendance: async () => {
    try {
      const emp = get().employee
      if (!emp) return
      const { selectedMonth, selectedYear } = get()
      const { from, to } = getMonthRange(selectedMonth, selectedYear)
      const res = await fetch('/api/attendance', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ employeeId: emp.id, from, to }),
      })
      if (res.ok) {
        const data = await res.json()
        set({ attendanceRecords: data.records || [] })
      }
    } catch {
      // silent
    }
  },
}))
