import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import {
  AttendanceStatus,
  getPayableValue,
  isValidDateString,
  parseDate,
  formatDate,
} from "@/lib/attendance";

// GET /api/attendance/[date]?employeeId=xxx
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ date: string }> }
) {
  try {
    const { date } = await params;

    if (!isValidDateString(date)) {
      return NextResponse.json(
        { error: "Invalid date format. Use YYYY-MM-DD" },
        { status: 400 }
      );
    }

    const { searchParams } = new URL(request.url);
    const employeeId = searchParams.get("employeeId");

    const where: Record<string, unknown> = { date };
    if (employeeId) {
      where.employeeId = employeeId;
    }

    const record = await db.attendance.findFirst({
      where,
      include: { employee: { select: { name: true } } },
    });

    if (!record) {
      return NextResponse.json(
        { error: "Attendance record not found for this date" },
        { status: 404 }
      );
    }

    return NextResponse.json({ record });
  } catch (error) {
    console.error("Error fetching attendance for date:", error);
    return NextResponse.json(
      { error: "Failed to fetch attendance record" },
      { status: 500 }
    );
  }
}

// PUT /api/attendance/[date] - Upsert attendance for a specific date
// Supports both creating new records and updating existing ones.
// Validates: date format, employee exists, date not before start date, valid status.
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ date: string }> }
) {
  try {
    const { date } = await params;

    if (!isValidDateString(date)) {
      return NextResponse.json(
        { error: "Invalid date format. Use YYYY-MM-DD" },
        { status: 400 }
      );
    }

    const body = await request.json();
    const { employeeId, status, isManualOverride, note } = body;

    if (!employeeId) {
      return NextResponse.json(
        { error: "employeeId is required" },
        { status: 400 }
      );
    }

    // Validate status
    if (!status || !Object.values(AttendanceStatus).includes(status)) {
      return NextResponse.json(
        {
          error: `Status is required and must be one of: ${Object.values(AttendanceStatus).join(", ")}`,
        },
        { status: 400 }
      );
    }

    // Check employee exists and get start date for validation
    const employee = await db.employee.findUnique({
      where: { id: employeeId },
    });

    if (!employee) {
      return NextResponse.json(
        { error: "Employee not found" },
        { status: 404 }
      );
    }

    // Validate that the date is not before the employee's start date
    const requestDate = parseDate(date);
    const employeeStart = parseDate(employee.startDate);
    if (requestDate < employeeStart) {
      return NextResponse.json(
        {
          error: `Date ${date} is before the employee's start date (${formatDate(employeeStart)}). Attendance cannot be recorded before the start date.`,
        },
        { status: 400 }
      );
    }

    const newStatus = status as AttendanceStatus;
    const payableValue = getPayableValue(newStatus);

    // Find existing record (unique constraint on date + employeeId)
    const existing = await db.attendance.findFirst({
      where: { date, employeeId },
    });

    if (existing) {
      // Update existing record
      const updateData: Record<string, unknown> = {
        status: newStatus,
        payableValue,
      };
      if (isManualOverride !== undefined) {
        updateData.isManualOverride = isManualOverride;
      }
      if (note !== undefined) {
        updateData.note = note;
      }

      const updated = await db.attendance.update({
        where: { id: existing.id },
        data: updateData,
      });

      return NextResponse.json({ record: updated, created: false });
    } else {
      // Create new record (upsert: create branch)
      const created = await db.attendance.create({
        data: {
          date,
          status: newStatus,
          payableValue,
          note: note ?? null,
          isAutoGenerated: false,
          isManualOverride: isManualOverride ?? true,
          employeeId,
        },
      });

      return NextResponse.json({ record: created, created: true }, { status: 201 });
    }
  } catch (error) {
    console.error("Error upserting attendance for date:", error);
    return NextResponse.json(
      { error: "Failed to update attendance record" },
      { status: 500 }
    );
  }
}

// DELETE /api/attendance/[date]?employeeId=xxx - Delete attendance for a specific date
export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ date: string }> }
) {
  try {
    const { date } = await params;

    if (!isValidDateString(date)) {
      return NextResponse.json(
        { error: "Invalid date format. Use YYYY-MM-DD" },
        { status: 400 }
      );
    }

    const { searchParams } = new URL(request.url);
    const employeeId = searchParams.get("employeeId");

    if (!employeeId) {
      return NextResponse.json(
        { error: "employeeId query parameter is required" },
        { status: 400 }
      );
    }

    const existing = await db.attendance.findFirst({
      where: { date, employeeId },
    });

    if (!existing) {
      return NextResponse.json(
        { error: "Attendance record not found for this date" },
        { status: 404 }
      );
    }

    await db.attendance.delete({
      where: { id: existing.id },
    });

    return NextResponse.json({
      message: `Attendance record for ${date} deleted successfully`,
    });
  } catch (error) {
    console.error("Error deleting attendance for date:", error);
    return NextResponse.json(
      { error: "Failed to delete attendance record" },
      { status: 500 }
    );
  }
}
