import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import {
  AttendanceStatus,
  FirstSundayPattern,
  getSundaysInRange,
  formatDate,
  generateSundayPattern,
  getPayableValue,
  isValidDateString,
  parseDate,
} from "@/lib/attendance";

/**
 * Calculate the global Sunday index for a given date.
 * This counts how many Sundays have occurred from a fixed anchor (e.g., 2000-01-02, first Sunday of 2000)
 * to the given date. This makes the alternating pattern consistent across months.
 */
function getGlobalSundayIndex(sundayDate: Date): number {
  // Anchor: 2000-01-02 is the first Sunday of 2000
  const anchor = new Date(2000, 0, 2);
  const diffMs = sundayDate.getTime() - anchor.getTime();
  const diffDays = Math.round(diffMs / (1000 * 60 * 60 * 24));
  return Math.floor(diffDays / 7);
}

/**
 * Determine the auto-status for a Sunday based on its global index and the pattern.
 */
function getAutoStatusForSunday(
  globalIndex: number,
  firstSundayPattern: FirstSundayPattern
): AttendanceStatus {
  if (firstSundayPattern === FirstSundayPattern.HALF_DAY) {
    // Even global index → HALF_DAY, Odd → OFF
    return globalIndex % 2 === 0 ? AttendanceStatus.HALF_DAY : AttendanceStatus.OFF;
  } else {
    // FULL_OFF: Even global index → OFF, Odd → HALF_DAY
    return globalIndex % 2 === 0 ? AttendanceStatus.OFF : AttendanceStatus.HALF_DAY;
  }
}

// GET /api/sunday?month=1&year=2025&employeeId=xxx&generateFuture=true
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const monthStr = searchParams.get("month");
    const yearStr = searchParams.get("year");
    const employeeId = searchParams.get("employeeId");
    const generateFuture = searchParams.get("generateFuture") === "true";

    if (!monthStr || !yearStr) {
      return NextResponse.json(
        { error: "month and year query parameters are required" },
        { status: 400 }
      );
    }

    const month = parseInt(monthStr, 10);
    const year = parseInt(yearStr, 10);

    if (isNaN(month) || month < 1 || month > 12) {
      return NextResponse.json(
        { error: "Month must be between 1 and 12" },
        { status: 400 }
      );
    }

    if (isNaN(year) || year < 1900 || year > 2100) {
      return NextResponse.json(
        { error: "Year must be a valid year" },
        { status: 400 }
      );
    }

    // Get employee
    let employee;
    if (employeeId) {
      employee = await db.employee.findUnique({ where: { id: employeeId } });
    } else {
      employee = await db.employee.findFirst();
    }

    if (!employee) {
      return NextResponse.json(
        { error: "Employee not found" },
        { status: 404 }
      );
    }

    // Get all Sundays in the month
    const startOfMonth = new Date(year, month - 1, 1);
    const daysInMonth = new Date(year, month, 0).getDate();
    const endOfMonth = new Date(year, month - 1, daysInMonth);

    const firstSundayPattern = employee.firstSundayPattern as FirstSundayPattern;
    const sundayPattern = generateSundayPattern(
      startOfMonth,
      endOfMonth,
      firstSundayPattern
    );

    // If generateFuture is true, auto-generate Sunday attendance records that don't exist yet
    if (generateFuture) {
      const sundayDates = sundayPattern.map((s) => s.date);
      const employeeStart = parseDate(employee.startDate);

      const existingRecords = await db.attendance.findMany({
        where: {
          employeeId: employee.id,
          date: { in: sundayDates },
        },
      });
      const existingDates = new Set(existingRecords.map((r) => r.date));

      const newRecords = sundayPattern
        .filter((sp) => {
          if (existingDates.has(sp.date)) return false;
          // Only generate for dates on or after employee start date
          const d = parseDate(sp.date);
          return d >= employeeStart;
        })
        .map((sp) => ({
          date: sp.date,
          status: sp.status,
          payableValue: getPayableValue(sp.status),
          isAutoGenerated: true,
          isManualOverride: false,
          employeeId: employee.id,
        }));

      if (newRecords.length > 0) {
        await db.attendance.createMany({ data: newRecords });
      }
    }

    // Get existing attendance records for Sundays in this month (refresh after potential generation)
    const sundayDates = sundayPattern.map((s) => s.date);
    const existingRecords = await db.attendance.findMany({
      where: {
        employeeId: employee.id,
        date: { in: sundayDates },
      },
    });

    const existingMap = new Map(existingRecords.map((r) => [r.date, r]));

    // Combine pattern with existing records, including pattern info
    const sundays = sundayPattern.map((sp, idx) => {
      const existing = existingMap.get(sp.date);
      const sundayDate = parseDate(sp.date);
      const globalIndex = getGlobalSundayIndex(sundayDate);

      return {
        date: sp.date,
        defaultStatus: sp.status,
        actualStatus: existing ? existing.status : sp.status,
        payableValue: existing ? existing.payableValue : getPayableValue(sp.status),
        isManualOverride: existing ? existing.isManualOverride : false,
        hasRecord: !!existing,
        // Pattern information
        patternInfo: {
          sundayNumberInMonth: idx + 1, // 1-based: 1st, 2nd, 3rd, 4th Sunday of the month
          globalSundayIndex: globalIndex, // Absolute index from anchor, for cross-month consistency
          autoStatus: getAutoStatusForSunday(globalIndex, firstSundayPattern),
          patternType: firstSundayPattern,
        },
      };
    });

    return NextResponse.json({
      employee: { id: employee.id, name: employee.name },
      month,
      year,
      firstSundayPattern,
      sundays,
      generated: generateFuture,
    });
  } catch (error) {
    console.error("Error fetching Sundays:", error);
    return NextResponse.json(
      { error: "Failed to fetch Sunday data" },
      { status: 500 }
    );
  }
}

// POST /api/sunday - Override a Sunday's attendance
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { employeeId, date, status } = body;

    if (!employeeId || !date || !status) {
      return NextResponse.json(
        { error: "employeeId, date, and status are required" },
        { status: 400 }
      );
    }

    if (!isValidDateString(date)) {
      return NextResponse.json(
        { error: "Date must be in YYYY-MM-DD format" },
        { status: 400 }
      );
    }

    // Verify it's a Sunday
    const parsedDate = parseDate(date);
    if (parsedDate.getDay() !== 0) {
      return NextResponse.json(
        { error: "The specified date is not a Sunday" },
        { status: 400 }
      );
    }

    if (!Object.values(AttendanceStatus).includes(status)) {
      return NextResponse.json(
        {
          error: `Status must be one of: ${Object.values(AttendanceStatus).join(", ")}`,
        },
        { status: 400 }
      );
    }

    // Check employee exists
    const employee = await db.employee.findUnique({
      where: { id: employeeId },
    });
    if (!employee) {
      return NextResponse.json(
        { error: "Employee not found" },
        { status: 404 }
      );
    }

    const payableValue = getPayableValue(status as AttendanceStatus);

    // Upsert the attendance record
    const existing = await db.attendance.findFirst({
      where: { date, employeeId },
    });

    let record;
    if (existing) {
      record = await db.attendance.update({
        where: { id: existing.id },
        data: {
          status,
          payableValue,
          isManualOverride: true,
        },
      });
    } else {
      record = await db.attendance.create({
        data: {
          date,
          status,
          payableValue,
          isAutoGenerated: false,
          isManualOverride: true,
          employeeId,
        },
      });
    }

    // Include pattern info in the response
    const firstSundayPattern = employee.firstSundayPattern as FirstSundayPattern;
    const globalIndex = getGlobalSundayIndex(parsedDate);

    return NextResponse.json({
      record,
      patternInfo: {
        globalSundayIndex: globalIndex,
        autoStatus: getAutoStatusForSunday(globalIndex, firstSundayPattern),
        patternType: firstSundayPattern,
      },
    });
  } catch (error) {
    console.error("Error overriding Sunday attendance:", error);
    return NextResponse.json(
      { error: "Failed to override Sunday attendance" },
      { status: 500 }
    );
  }
}

// DELETE /api/sunday?employeeId=xxx&month=1&year=2025
// Reset all Sunday manual overrides for a given month
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const employeeId = searchParams.get("employeeId");
    const monthStr = searchParams.get("month");
    const yearStr = searchParams.get("year");

    if (!employeeId) {
      return NextResponse.json(
        { error: "employeeId is required" },
        { status: 400 }
      );
    }

    const employee = await db.employee.findUnique({
      where: { id: employeeId },
    });
    if (!employee) {
      return NextResponse.json(
        { error: "Employee not found" },
        { status: 404 }
      );
    }

    // Determine the date range
    let fromStr: string;
    let toStr: string;

    if (monthStr && yearStr) {
      const month = parseInt(monthStr, 10);
      const year = parseInt(yearStr, 10);
      fromStr = `${year}-${String(month).padStart(2, "0")}-01`;
      const daysInMonth = new Date(year, month, 0).getDate();
      toStr = `${year}-${String(month).padStart(2, "0")}-${String(daysInMonth).padStart(2, "0")}`;
    } else {
      return NextResponse.json(
        { error: "month and year query parameters are required" },
        { status: 400 }
      );
    }

    const firstSundayPattern = employee.firstSundayPattern as FirstSundayPattern;
    const startOfMonth = parseDate(fromStr);
    const endOfMonth = parseDate(toStr);

    // Get the default Sunday pattern for the month
    const sundayPattern = generateSundayPattern(
      startOfMonth,
      endOfMonth,
      firstSundayPattern
    );

    // Find all manually overridden Sunday records
    const sundayDates = sundayPattern.map((s) => s.date);
    const overriddenRecords = await db.attendance.findMany({
      where: {
        employeeId,
        date: { in: sundayDates },
        isManualOverride: true,
      },
    });

    if (overriddenRecords.length === 0) {
      return NextResponse.json({
        message: "No manual overrides to reset",
        resetCount: 0,
      });
    }

    // Reset each overridden Sunday to its default pattern status
    const patternMap = new Map(sundayPattern.map((s) => [s.date, s.status]));
    let resetCount = 0;

    for (const record of overriddenRecords) {
      const defaultStatus = patternMap.get(record.date);
      if (defaultStatus) {
        await db.attendance.update({
          where: { id: record.id },
          data: {
            status: defaultStatus,
            payableValue: getPayableValue(defaultStatus),
            isManualOverride: false,
            isAutoGenerated: true,
          },
        });
        resetCount++;
      }
    }

    return NextResponse.json({
      message: `Reset ${resetCount} Sunday overrides to auto-generated pattern`,
      resetCount,
    });
  } catch (error) {
    console.error("Error resetting Sunday overrides:", error);
    return NextResponse.json(
      { error: "Failed to reset Sunday overrides" },
      { status: 500 }
    );
  }
}
